#!/bin/bash

# This script sources additional bash completion scripts and contains some
# custom completions for commands not installed.

source ~/.bash_config/npm-completion.bash
source ~/.bash_config/pip-completion.bash
source ~/.bash_config/git-completion.bash
